
INSERT INTO songs (title, artist, genre, difficulty_level)
VALUES
('Shape of You', 'Ed Sheeran', 'Pop', 'easy'),
('Blinding Lights', 'The Weeknd', 'Pop', 'easy'),
('Uptown Funk', 'Mark Ronson ft. Bruno Mars', 'Pop', 'easy'),
('Shake It Off', 'Taylor Swift', 'Pop', 'easy'),
('Call Me Maybe', 'Carly Rae Jepsen', 'Pop', 'easy'),
('Counting Stars', 'OneRepublic', 'Rock', 'easy'),
('Rolling in the Deep', 'Adele', 'Rock', 'easy'),
('Someone Like You', 'Adele', 'Rock', 'easy'),
('Photograph', 'Ed Sheeran', 'Rock', 'easy'),
('Firework', 'Katy Perry', 'Rock', 'easy'),
('Despacito', 'Luis Fonsi ft. Daddy Yankee', 'Hip-Hop/Rap', 'easy'),
('Stay', 'Rihanna ft. Mikky Ekko', 'Hip-Hop/Rap', 'easy'),
('Senorita', 'Shawn Mendes & Camila Cabello', 'Hip-Hop/Rap', 'easy'),
('Cheap Thrills', 'Sia', 'Hip-Hop/Rap', 'easy'),
('Bad Guy', 'Billie Eilish', 'Hip-Hop/Rap', 'easy'),
('Perfect', 'Ed Sheeran', 'Country', 'easy'),
('Hello', 'Adele', 'Country', 'easy'),
('All of Me', 'John Legend', 'Country', 'easy'),
('Love Yourself', 'Justin Bieber', 'Country', 'easy'),
('Happy', 'Pharrell Williams', 'Country', 'easy');

INSERT INTO songs (title, artist, genre, difficulty_level)
VALUES
('Just the Way You Are', 'Bruno Mars', 'Pop', 'medium'),
('Grenade', 'Bruno Mars', 'Pop', 'medium'),
('Roar', 'Katy Perry', 'Pop', 'medium'),
('Let Her Go', 'Passenger', 'Pop', 'medium'),
('You Belong With Me', 'Taylor Swift', 'Pop', 'medium'),
('Chasing Cars', 'Snow Patrol', 'Rock', 'medium'),
('Boulevard of Broken Dreams', 'Green Day', 'Rock', 'medium'),
('The Middle', 'Jimmy Eat World', 'Rock', 'medium'),
('Say You Won''t Let Go', 'James Arthur', 'Rock', 'medium'),
('Before You Go', 'Lewis Capaldi', 'Rock', 'medium'),
('Take Me to Church', 'Hozier', 'Hip-Hop/Rap', 'medium'),
('Apologize', 'Timbaland ft. OneRepublic', 'Hip-Hop/Rap', 'medium'),
('Bleeding Love', 'Leona Lewis', 'Hip-Hop/Rap', 'medium'),
('Meant to Be', 'Bebe Rexha ft. Florida Georgia Line', 'Hip-Hop/Rap', 'medium'),
('When I Was Your Man', 'Bruno Mars', 'Hip-Hop/Rap', 'medium'),
('Demons', 'Imagine Dragons', 'Country', 'medium'),
('Need You Now', 'Lady A', 'Country', 'medium'),
('I Knew You Were Trouble', 'Taylor Swift', 'Country', 'medium'),
('Locked Out of Heaven', 'Bruno Mars', 'Country', 'medium'),
('A Thousand Years', 'Christina Perri', 'Country', 'medium');

INSERT INTO songs (title, artist, genre, difficulty_level)
VALUES
('Super Bass', 'Nicki Minaj', 'Pop', 'hard'),
('I Write Sins Not Tragedies', 'Panic! At The Disco', 'Pop', 'hard'),
('Mr. Brightside', 'The Killers', 'Pop', 'hard'),
('Hook', 'Blues Traveler', 'Pop', 'hard'),
('Semi-Charmed Life', 'Third Eye Blind', 'Pop', 'hard'),
('American Pie', 'Don McLean', 'Rock', 'hard'),
('We Didn''t Start the Fire', 'Billy Joel', 'Rock', 'hard'),
('Bohemian Rhapsody', 'Queen', 'Rock', 'hard'),
('Basket Case', 'Green Day', 'Rock', 'hard'),
('The Man', 'The Killers', 'Rock', 'hard'),
('Rap God', 'Eminem', 'Hip-Hop/Rap', 'hard'),
('Godzilla', 'Eminem ft. Juice WRLD', 'Hip-Hop/Rap', 'hard'),
('The Real Slim Shady', 'Eminem', 'Hip-Hop/Rap', 'hard'),
('It''s the End of the World as We Know It', 'R.E.M.', 'Hip-Hop/Rap', 'hard'),
('Blinded by the Light', 'Manfred Mann''s Earth Band', 'Hip-Hop/Rap', 'hard'),
('End of the Line', 'Traveling Wilburys', 'Country', 'hard'),
('Life Is a Highway', 'Tom Cochrane', 'Country', 'hard'),
('The Impression That I Get', 'The Mighty Mighty Bosstones', 'Country', 'hard'),
('The Humpty Dance', 'Digital Underground', 'Country', 'hard'),
('One Week', 'Barenaked Ladies', 'Country', 'hard');
